-- 서울시 「의료관광 협력기관 · 병·의원」 목록 100건.
-- medical.visitseoul.net 에서 2026-08-18 에 받았다. 만든 스크립트는 저장소 밖에 있고,
-- 이 파일이 그 결과다 — 다시 받으면 이 파일의 차이로 무엇이 달라졌는지 보인다.
--
-- 여기 실린 곳은 **실재하는 기관**이다. 그래서 없는 등록번호를 지어 넣지 않는다.
-- promotion_reg_no 는 전부 NULL 이고, 배지는 source = 'SEOUL' 로 서울시 목록을
-- 근거로 붙는다. source_url 로 누구나 원문을 눌러 대조할 수 있다.
--
-- org_name_en 도 NULL 이다. 서울시 목록에 영문명이 없고, 협회가 로마자로 옮겨
-- 적으면 기관이 쓰지 않는 이름을 협회가 지어낸 것이 된다 (7장).
--
-- 이메일과 전화번호는 상세 페이지에 있지만 가져오지 않았다. 화면이 쓰지 않는 데다,
-- 받아 두면 지킬 것만 늘어난다 (27장).

INSERT INTO member_corp (member_id, org_name, org_name_en, promotion_reg_no, specialties, address, website, org_type) VALUES
 ('VS2303','헤스티아 여성의원',NULL,NULL,'Other','서울특별시 강남구 도산대로 119','https://hestia-womenclinic.co.kr/','CLINIC'),
 ('VS2302','허쉬성형외과',NULL,NULL,'Plastic surgery','서울시 강남구 삼성로 730','https://www.hershe9.com/','CLINIC'),
 ('VS2301','한국의료재단 IFC 종합검진센터',NULL,NULL,'Health screening','서울시 영등포구 국제금융로 10','https://komef.org/','CLINIC'),
 ('VS2300','픽셀랩성형외과의원',NULL,NULL,'Plastic surgery','서울 서초구 서초대로73길 42','http://www.pixelab.co.kr','CLINIC'),
 ('VS2299','프레쉬 홍닥터의원',NULL,NULL,'Plastic surgery','서울 강남구 도산대로 165','https://www.freshps.com/','CLINIC'),
 ('VS2298','페이브피부과의원',NULL,NULL,'Dermatology','서울특별시 용산구 한강대로 69','https://faveclinic.com','CLINIC'),
 ('VS2297','퍼스트삼성안과의원',NULL,NULL,'Ophthalmology','서울특별시 서초구 서초대로78길 22','https://www.firstsamsung.com/','CLINIC'),
 ('VS2296','탑페이스성형외과의원',NULL,NULL,'Plastic surgery','서울 강남구 논현로164길 19','https://www.topfaceps.com/','CLINIC'),
 ('VS2294','최혁한의원',NULL,NULL,'Korean medicine','서울시 동대문구 약령동길 52','https://www.instagram.com/choi__hyeok/','CLINIC'),
 ('VS2293','청아연의원',NULL,NULL,'Dermatology','서울특별시 강남구 강남대로 584','https://www.purehealing.co.kr','CLINIC'),
 ('VS2292','청담 에끌라드 의원',NULL,NULL,'Dermatology','서울특별시 강남구 도산대로 420','http://eclatde.com','CLINIC'),
 ('VS2291','줌 구강악안면외과 치과의원',NULL,NULL,'Dentistry','서울시 강남구 논현로 857','http://thebestoms.com/','CLINIC'),
 ('VS2290','KMI한국의학연구소 광화문센터',NULL,NULL,'Health screening','서울특별시 종로구 세종대로 149','https://www.kmi.or.kr/center/gwanghwamun','CLINIC'),
 ('VS2289','장주혜치과의원',NULL,NULL,'Dentistry','서울특별시 종로구 새문안로 5길 31','https://cjhdental.com/','CLINIC'),
 ('VS2288','이비엠한의원',NULL,NULL,'Korean medicine','서울시 서초구 서초대로 50길 8','https://ebmkorea.com/','CLINIC'),
 ('VS2287','유앤린성형외과',NULL,NULL,'Plastic surgery','서울 강남구 논현로848','http://unlinps.kr/','CLINIC'),
 ('VS2286','원더풀 성형외과',NULL,NULL,'Plastic surgery','서울특별시 서초구 강남대로 419','https://wonderfulps.com/','CLINIC'),
 ('VS2285','우주연한의원',NULL,NULL,'Korean medicine','서울 특별시 종로구 북촌로 12길 41','https://blog.naver.com/woojooclinic','CLINIC'),
 ('VS2284','온아치과의원',NULL,NULL,'Dentistry','서울특별시 도봉구 마들로 13길 61','http://onagangbuk.com/','CLINIC'),
 ('VS2283','오늘성형외과의원',NULL,NULL,'Plastic surgery','서울시 강남구 강남대로 596','https://onulps.com/','CLINIC'),
 ('VS2282','아너스티성형외과',NULL,NULL,'Plastic surgery','서울시 서초구 강남대로589',NULL,'CLINIC'),
 ('VS2281','신소애여성의원 SINSOE WOMEN''S CLINIC',NULL,NULL,'Other','서울특별시 강남구 논현로537',NULL,'CLINIC'),
 ('VS2279','서울재생치과의원',NULL,NULL,'Dentistry','서울시 서대문구 신촌로93',NULL,'CLINIC'),
 ('VS2278','삼성미라클안과',NULL,NULL,'Ophthalmology','서울시 강남구 테헤란로 115',NULL,'CLINIC'),
 ('VS2277','비오페이스의원',NULL,NULL,'Dermatology','서울특별시 서초구 강남대로 605',NULL,'CLINIC'),
 ('VS2276','블레싱피부과의원',NULL,NULL,'Dermatology','서울특별시 서초구 반포대로 291',NULL,'CLINIC'),
 ('VS2275','본라인한의원(을지로)',NULL,NULL,'Korean medicine','서울시 종로구 청계천로 73, 장통빌딩 3층',NULL,'CLINIC'),
 ('VS2273','베리굿성형외과의원',NULL,NULL,'Plastic surgery','서울 강남구 논현로 635 우림빌딩',NULL,'CLINIC'),
 ('VS2272','리아한의원(명동점)',NULL,NULL,'Korean medicine','서울특별시 중구 명동8가길 27',NULL,'CLINIC'),
 ('VS2271','맥스구강악안면외과치과의원',NULL,NULL,'Dentistry','서울시 서초구 강남대로 407',NULL,'CLINIC'),
 ('VS2269','르치과의원',NULL,NULL,'Dentistry','서울시 강남구 봉은사로108',NULL,'CLINIC'),
 ('VS2268','로앤산부인과의원',NULL,NULL,'Other','서울특별시 서초구 강남대로 403',NULL,'CLINIC'),
 ('VS2267','디엠피부과의원',NULL,NULL,'Dermatology','서울시 강남구 압구정로158 진우빌딩 4층',NULL,'CLINIC'),
 ('VS2266','디에이성형외과',NULL,NULL,'Plastic surgery','서울시 강남구 테헤란로 125',NULL,'CLINIC'),
 ('VS2265','드림헤어라인의원',NULL,NULL,'Other','서울 강남구 테헤란로25길 43',NULL,'CLINIC'),
 ('VS2264','더끌림산부인과',NULL,NULL,'Other','서울시 중구 퇴계로109',NULL,'CLINIC'),
 ('VS2262','다이트한의원',NULL,NULL,'Korean medicine','서울특별시 강남구 도산대로 121',NULL,'CLINIC'),
 ('VS2238','기린성형외과',NULL,NULL,'Plastic surgery','서울시 서초구 서초대로77길 54',NULL,'CLINIC'),
 ('VS2237','글로리서울안과',NULL,NULL,'Ophthalmology','서울시 서초구 서초대로74길3',NULL,'CLINIC'),
 ('VS2236','강남도쿄안과',NULL,NULL,'Ophthalmology','서울시 강남구 강남대로 372',NULL,'CLINIC'),
 ('VS2235','강남큐브안과',NULL,NULL,'Ophthalmology','서울 강남구 선릉로 703',NULL,'CLINIC'),
 ('VS2234','강남조은눈안과',NULL,NULL,'Ophthalmology','서울시 강남구 테헤란로 107',NULL,'CLINIC'),
 ('VS2233','강남아이원스안과',NULL,NULL,'Ophthalmology','서울 서초구 사평대로 368',NULL,'CLINIC'),
 ('VS2232','강남센트럴안과',NULL,NULL,'Ophthalmology','서울 강남구 테헤란로 333',NULL,'CLINIC'),
 ('VS2231','강남브랜드안과',NULL,NULL,'Ophthalmology','서울 서초구 강남대로 519',NULL,'CLINIC'),
 ('VS2230','강남그랜드안과',NULL,NULL,'Ophthalmology','서울특별시 서초구 강남대로 363',NULL,'CLINIC'),
 ('VS2229','강남 아름다운나라 피부과',NULL,NULL,'Dermatology','서울특별시 강남구 강남대로 390',NULL,'CLINIC'),
 ('VS2228','청담해리슨병원',NULL,NULL,'Orthopedics','서울특별시 강남구 삼성로 646',NULL,'CLINIC'),
 ('VS2227','신세계서울병원',NULL,NULL,'Hospital','서울 영등포구 경인로 841',NULL,'HOSPITAL'),
 ('VS2226','성모진안과',NULL,NULL,'Ophthalmology','서울시 서초구 강남대로 337',NULL,'CLINIC'),
 ('VS2225','서울미즈병원',NULL,NULL,'Hospital','서울특별시 강동구 천호대로 1041',NULL,'HOSPITAL'),
 ('VS2224','미니쉬치과병원',NULL,NULL,'Dentistry','서울특별시 강남구 언주로 728',NULL,'CLINIC'),
 ('VS2223','리드힐병원',NULL,NULL,'Hospital','서울특별시 은평구 연서로10',NULL,'HOSPITAL'),
 ('VS2222','강남제이에스병원',NULL,NULL,'Orthopedics','서울시 강남구 도곡로 122',NULL,'CLINIC'),
 ('VS2221','대림성모병원',NULL,NULL,'General hospital','서울 영등포구 시흥대로 657',NULL,'HOSPITAL'),
 ('VS2111','강산한의원',NULL,NULL,'Korean medicine','서울시 강서구 강서로45길 13',NULL,'CLINIC'),
 ('VS106','자생한방병원',NULL,NULL,'Korean medicine','서울시 강남구 강남대로 536',NULL,'CLINIC'),
 ('VS15','대항병원',NULL,NULL,'Hospital','서울특별시 서초구 남부순환로 2151',NULL,'HOSPITAL'),
 ('VS121','강남베드로종합병원',NULL,NULL,'General hospital','서울 강남구 남부순환로 2633',NULL,'HOSPITAL'),
 ('VS55','밝은눈안과의원 잠실롯데타워점',NULL,NULL,'Ophthalmology','서울 송파구 올림픽로 300',NULL,'CLINIC'),
 ('VS72','르미엘성형외과',NULL,NULL,'Plastic surgery','서울시 종로구 종로 120',NULL,'CLINIC'),
 ('VS74','리즈산부인과',NULL,NULL,'Other','서울시 강남구 도산대로 127',NULL,'CLINIC'),
 ('VS39','티제이성형외과의원',NULL,NULL,'Plastic surgery','서울특별시 강남구 강남대로 606',NULL,'CLINIC'),
 ('VS98','예송이비인후과',NULL,NULL,'Other','서울시 강남구 삼성로773',NULL,'CLINIC'),
 ('VS84','닥터디자이너의원',NULL,NULL,'Dermatology','서울 영등포구 경인로 870',NULL,'CLINIC'),
 ('VS118','한국원자력의학원 원자력병원',NULL,NULL,'General hospital','서울 노원구 노원로 75',NULL,'HOSPITAL'),
 ('VS12','한양대학교병원',NULL,NULL,'Tertiary hospital','서울 성동구 왕십리로 222-1',NULL,'HOSPITAL'),
 ('VS38','에스플란트치과병원',NULL,NULL,'Dentistry','서울시 강남구 도산대로 410',NULL,'CLINIC'),
 ('VS19','순천향대학교 부속 서울병원',NULL,NULL,'General hospital','서울특별시 용산구 대사관로 59',NULL,'HOSPITAL'),
 ('VS40','우리들병원',NULL,NULL,'Orthopedics','서울시 강남구 학동로 445',NULL,'CLINIC'),
 ('VS24','한림대학교한강성심병원',NULL,NULL,'General hospital','서울시 영등포구 버드나루로7길 12',NULL,'HOSPITAL'),
 ('VS128','힐링안과의원',NULL,NULL,'Ophthalmology','서울 강남구 강남대로 470 808타워',NULL,'CLINIC'),
 ('VS113','청담엔비의원',NULL,NULL,'Plastic surgery','서울특별시 강남구 삼성로 772',NULL,'CLINIC'),
 ('VS9','세브란스병원',NULL,NULL,'Tertiary hospital','서울시 서대문구 연세로 50-1',NULL,'HOSPITAL'),
 ('VS18','우리들병원 (서울김포공항)',NULL,NULL,'General hospital','서울특별시 강서구 하늘길 70',NULL,'HOSPITAL'),
 ('VS41','한신메디피아의원',NULL,NULL,'Health screening','서울특별시 서초구 잠원로 94',NULL,'CLINIC'),
 ('VS1118','이문원 한의원',NULL,NULL,'Korean medicine','서울 강남구 선릉로132길 33',NULL,'CLINIC'),
 ('VS1','가톨릭대학교 서울성모병원',NULL,NULL,'Tertiary hospital','서울 서초구 반포대로 222',NULL,'HOSPITAL'),
 ('VS11','중앙대학교병원',NULL,NULL,'Tertiary hospital','서울시 동작구 흑석로 102',NULL,'HOSPITAL'),
 ('VS8','서울아산병원',NULL,NULL,'Tertiary hospital','서울특별시 송파구 올림픽로43길 88',NULL,'HOSPITAL'),
 ('VS7','서울대학교병원',NULL,NULL,'Tertiary hospital','서울시 종로구 대학로 101',NULL,'HOSPITAL'),
 ('VS50','JW정원성형외과의원',NULL,NULL,'Plastic surgery','서울 강남구 삼성로 553',NULL,'CLINIC'),
 ('VS5','고려대학교 안암병원',NULL,NULL,'Tertiary hospital','서울 성북구 고려대로 73',NULL,'HOSPITAL'),
 ('VS4','경희의료원',NULL,NULL,'Tertiary hospital','서울특별시 동대문구 경희대로 23',NULL,'HOSPITAL'),
 ('VS3','건국대학교병원',NULL,NULL,'Tertiary hospital','서울특별시 광진구 능동로 120-1',NULL,'HOSPITAL'),
 ('VS2','강남세브란스병원',NULL,NULL,'Tertiary hospital','서울특별시 강남구 언주로 211',NULL,'HOSPITAL'),
 ('VS6','삼성서울병원',NULL,NULL,'Tertiary hospital','서울시 강남구 일원로 81',NULL,'HOSPITAL'),
 ('VS25','건양의료재단 김안과병원',NULL,NULL,'Hospital','서울특별시 영등포구 영신로 136',NULL,'HOSPITAL'),
 ('VS21','의료법인 서울효천의료재단 에이치플러스 양지병원',NULL,NULL,'General hospital','서울특별시 관악구 남부순환로 1636',NULL,'HOSPITAL'),
 ('VS20','CM(씨엠)병원',NULL,NULL,'General hospital','서울특별시 영등포구 영등포로36길 13',NULL,'HOSPITAL'),
 ('VS17','서울부민병원',NULL,NULL,'General hospital','서울시 강서구 공항대로 389',NULL,'HOSPITAL'),
 ('VS16','미즈메디병원',NULL,NULL,'General hospital','서울 강서구 강서로 295',NULL,'HOSPITAL'),
 ('VS14','강동경희대학교병원 (KUIMS)',NULL,NULL,'General hospital','서울특별시 강동구 동남로 892',NULL,'HOSPITAL'),
 ('VS13','가톨릭대학교 여의도성모병원',NULL,NULL,'General hospital','서울특별시 영등포구 63로 10',NULL,'HOSPITAL'),
 ('VS68','드림성모안과의원',NULL,NULL,'Ophthalmology','서울특별시 강남구 강남대로 390',NULL,'CLINIC'),
 ('VS67','더스퀘어치과의원',NULL,NULL,'Dentistry','서울시 종로구 종로3길17',NULL,'CLINIC'),
 ('VS65','제이씨빛소망안과',NULL,NULL,'Ophthalmology','서울시 영등포구 국제금융로6길 33',NULL,'CLINIC'),
 ('VS64','Note Plastic Surgery',NULL,NULL,'Plastic surgery','563 Gangnam-daero, Seocho-gu, Seoul',NULL,'CLINIC'),
 ('VS62','대영성형외과의원',NULL,NULL,'Plastic surgery','서울특별시 강남구 압구정로 338',NULL,'CLINIC'),
 ('VS63','와이즈유의원',NULL,NULL,'Plastic surgery','서울특별시 중구 명동8가길 52',NULL,'CLINIC');

INSERT INTO medicheck_listing (member_id, listed, verified_at, verified_by, source, source_url, region, languages, intro_ko, updated_at) VALUES
 ('VS2303',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2303','강남구','English, Chinese','헤스티아여성의원은 질성형·소음순/대음순수술 등 여성 성형을 특화로 진료하는 여성성형 전문병원입니다. 전문 검사 장비로 측정한 결과를 기반으로 1:1 맞춤 진료를 진행하고, 이에 따른 치료 방법을 권유합니다. / 대표원장 책임 진료시스템으로, 상담부터 수술·소독·봉합·후관리까지 책임 있게 진행합니다. / 최첨단 장비는 물론 CCTV, 수술 환자 상태 모니터링 기기 등 체계적인 시스템을 갖추고 고객의 안전을 책임집니다.','2026-08-18'),
 ('VS2302',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2302','강남구','English, Chinese, Japanese, Indonesian','허쉬성형외과는 안티에이징 수술 전문병원으로, 의료진 전원이 숙련된 성형외과 전문의로 구성되어 있습니다. / 안정적이고 자연스러운 결과를 추구하는 성형외과 의원으로, 강남의 패션· 엔터테인트먼트 산업의 중심인 청담동에 위치합니다. 허쉬성형외과는 51개국의 외국인 고객이 찾은 병원으로, 대한민국 보건산업 대상(5회)과 보건복지부장관상을 수상했으며, 외국인 환자 서비스 대상 2회(강남구), 의료관광산업 공로패를 수상했습니다.','2026-08-18'),
 ('VS2301',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2301','영등포구','English','첨단 의료기술과 장비를 갖춘 한국의료재단 IFC종합검진센터는 양질의 의료서비스를 통해 고객 가치를 실현하는 의료기관입니다. ''행복은 건강이라는 나무에서 피어나는 꽃이다''라는 말처럼 건강의 파수꾼으로 행복한 세상을 만드는 데 최선을 다하고 있으며, 수준 높은 진료와 사랑의 실천으로 인류의 건강한 삶을 추구하고 국민으로부터 사랑받는 의료기관이 되기 위해 노력하겠습니다.','2026-08-18'),
 ('VS2300',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2300','서초구','English, Chinese, Japanese, French','미용에 관한 전반적인 시술 및 수술을 모두 취급하는 픽셀랩성형외과는 뛰어난 실력을 갖춘 의료진과 쾌적한 시설을 보유하고 있습니다. 최근에는 수술보다 간편한 시술이 대세인 만큼, 실리프팅부터 레이저 리프팅(HIFU, RF 포함), 필러, 보톡스, 흉터 제거, 레이저 제모, 스킨부스터, 지방분해 관련 시술(지방 분해 주사, 지방 흡입 등), 콜라겐 부스터, 토닝, 지방이식, 문신·점 제거, 탈모, 다이어트 치료 등 다양한 시술을 제공합니다. 수술 분야는 지방 흡입은 물론 눈·코·지방이식·가슴 확대·거상 등 모든 분야를 다룹니다.','2026-08-18'),
 ('VS2299',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2299','강남구','English, Chinese, Japanese, Russian','프레쉬홍닥터의원은 병원을 찾는 환자들이 만족스러온 결과를 얻을 수 있도록 끊임없이 연구하고 최신 경향을 파악합니다. 자연스러운 아름다움을 추구하는 프레쉬는 환자를 가족처럼 생각하며, 조화롭고 자연스러운 아름다움을 찾아드리기 위해 노력합니다.','2026-08-18'),
 ('VS2298',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2298','용산구','English, Chinese, Japanese','소중한 아름다움을 선사하는 페이브피부과의원은 피부과 전문의이자 맞춤형 화장품 조제 관리사인 손지희 원장이 직접 진료하고 시술합니다. 피부과 전문병원으로, 비수술 윤곽 개선, 리프팅, 여드름, 색소 치료, 탈모, 비만, 바디 관리, 항산화 수액 치료 등 피부와 관련된 모든 치료를 제공합니다. / 영어와 중국어, 일본어를 지원해 외국인 환자도 편하게 진료 받을 수 있으며, 이미 많은 환자가 찾고 있습니다. 또한 쾌적한 환경과 최신 장비를 통해 더욱 편안한 진료를 제공합니다. / EMFACE 엠페이스, Titanium 티타늄 리프팅 Accent Prime Tuneface 악센트 프라임 튠페이스 Ultherapy 울쎄라 등 안티에이징 맞춤시술은 환자에게 높은 만족을 제공합니다. 방문 당일 상담부터 시술, 관리까지의 원스톱 서비스로 효율성을 극대화하고 있으며, 카카오톡, 인스타그램, 라인 등 다양한 채널의 SNS로 사후관리 정보를 제공합니다.','2026-08-18'),
 ('VS2297',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2297','서초구','English, Russian, Korean, Uzbek','퍼스트삼성안과 의료진은 수준 높은 의료서비스를 제공하기 위해 노력합니다. 이를 위해 끊임없는 연구 및 학술 활동을 통해 매년 국제학술지에 논문을 게재하고 있습니다. / 퍼스트삼성안과는 고난도 수술 의뢰를 받을 정도로 뛰어난 실력을 갖추고 있습니다. 20년 간 백내장, 시력 교정술, 망막수술 총 10만 건 이상의 수술 경험을 가진 의료진이 환자의 부작용 없는 안전한 수술을 담당합니다. 의료진은 환자의 눈 상태를 정확하게 파악하고 수술 전 검사부터 수술 후 관리까지 책임지고 있습니다. 또한 모든 안과 질환의 검사·수술이 가능한 최신 장비를 갖추고 있습니다.','2026-08-18'),
 ('VS2296',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2296','강남구','English, Chinese, Japanese','압구정역 3번 출구에 위치한 탑페이스성형외과는 눈·코 재수술과 리프팅에 특화된 전문병원입니다. 탑페이스성형외과 의료진은 풍부한 경험과 숙련된 노하우로 안전하고 만족감 높은 수술을 위해 최선을 다하고 있습니다. / 또한 철저한 안전 규칙 하에 다양한 안전시스템을 구축, 운영하고 있습니다. 전 수술실에 CCTV가 설치되어 있어 모든 수술 과정이 실시간으로 녹화되는 투명하고 안전한 병원입니다. / 내면의 치유를 통한 개성 있는 아름다움, 탑페이스성형외과의 모토입니다.','2026-08-18'),
 ('VS2294',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2294','동대문구','Japanese','최혁한의원은 일본 관광객과 한국 거주 일본인에게 입소문으로 알려져 유명해진 곳입니다. 피부미용, 주름 개선, 다이어트 등을 중점적으로 치료하고 있습니다.','2026-08-18'),
 ('VS2293',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2293','강남구','English, Japanese','청아연의원은 ‘건강한 아름다움’을 모토로 이너뷰티와 안티에이징에 특화되어 있습니다. 외국인 고객에게는 3가지 클리닉을 제시합니다. 첫째, 고압산소치료와 붓기 수액입니다. 두 치료는 성형수술을 받으신 외국인 고객이 빠르게 회복하고 한국에서 관광을 즐길 수 있도록 도와줍니다. 둘째, 무통스킨부스터 시스템입니다. 청아연의원은 적은 통증으로 리쥬란, 쥬베룩 등 스킨부스터를 주입하는 무통스킨부스터 시스템에 대한 특허를 보유하고 있습니다. 셋째, 리프팅 클리닉입니다. 청아연의원의 원장은 실리프팅의 키닥터이며, 울쎄라, 인모드 등 레이저리프팅 시술에 대해서도 인증 받은 전문가입니다.','2026-08-18'),
 ('VS2292',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2292','강남구','English, Chinese, Japanese','청담에끌라드의원은 피부 전문 의료진이 1:1 맞춤 솔루션을 제공, 건강하고 아름다운 피부를 만들 수 있도록 최선을 다합니다. 박소윤 대표원장은 국제 미용항노화학회, 한국 미용외과의학회, 한국 영양의학회의 이사이자, 올리지오· 울트라브이·리쥬란·LDM·스킨아우라·엘리시스센스 등의 키닥터이며 해외 키닥터 교육을 담당하고 있습니다. 대표원장의 섬세하고 전문적인 리프팅, 쁘띠성형, 스킨부스팅, 안티에이징 맞춤시술은 환자에게 높은 만족을 제공합니다. 방문 당일 상담부터 시술, 관리까지의 원스톱 서비스로 효율성을 극대화하고 있으며, 카카오톡, 인스타그램, 라인 등 다양한 채널의 SNS로 사후관리 정보를 제공합니다.','2026-08-18'),
 ('VS2291',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2291','강남구','English, Chinese, Japanese','줌 구강악안면외과는 국제구강악안면외과 전문의, 보건복지부 인증 구강악안면외과 전문의가 진료하는 압구정 최초의 구강악안면외과 치과의원입니다. / 다양한 임상·수술 경험을 가진 대학병원 교수 출신 전문의가 꾸준한 연구활동을 통해 만족스러운 수술 결과를 내기 위해 최선을 다합니다. 또한 안전하고 정확한 수술을 위해 첨단 의료영상장비와 체계화된 안전시스템을 갖추고 있습니다. 마취통증의학과 전문의가 수술 전 과정에 걸쳐 환자 상태를 모니터링, 안전한 수술을 지원합니다. 각 분야 전문의로 구성된 ‘악안면기형연구소’를 통해 환자 특성에 맞는 치료법을 찾기 위해 고민하는 병원, 환자의 안전을 최우선으로 생각하는 병원이 되겠습니다.','2026-08-18'),
 ('VS2290',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2290','종로구','English, Chinese, Mongolian','국내 종합검진 대중화에 앞장서 온 한국의학연구소(KMI)는 서울부터 제주까지 전국 8개 지역에서 질병 예방과 조기 발견을 위한 건강검진센터를 운영하고 있습니다. / KMI는 국민건강 증진을 위한 다양한 활동·연구를 지원하고 취약 계층을 위한 프로그램을 진행함으로써 건강한 사회를 만드는 데 기여합니다. / 또한 40년간 쌓아온 건강검진 역량과 서비스, 브랜드 가치를 강화해 앞으로도 국민건강을 지키며 사회적 책임을 다하는 ‘평생 건강관리 파트너’이자 / ‘K-건강검진’을 선도하는 기관이 되도록 최선을 다하겠습니다.','2026-08-18'),
 ('VS2289',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2289','종로구','English','장주혜치과의원은 서울대학교치과병원 교수로 17년간 재직한 장주혜 원장이 이끄는 병원으로, 최신 과학적 근거에 기반 한 교과서적 진료를 지향합니다. / 장주혜 원장은 서울대학교치과대학 졸업, 미국 인디애나 치과대학 레지던트 수료, 미국 보존수복학 전문의 및 보건복지부인증 치과보존과 전문의 자격을 보유하고 있습니다. 서울대학교치과병원 재직 중에 외국인 환자 진료에 특화된 TRICARE OCONUS Preferred Dentist로 지정되어 진료했습니다. / 광화문 세종문화회관 옆 센터포인트광화문 빌딩에 위치하며 첨단 디지털 의료 장비를 통한 최신 임상 기술을 구현함으로써 한국 치과 의료의 수준 높은 위상을 보여줍니다.','2026-08-18'),
 ('VS2288',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2288','서초구','English, Japanese','이비엠한의원은 대사·면역력 회복을 위한 식품 치료를 특화로 하는 병원입니다. 몸에 맞는 음식으로 당뇨, 고지혈증 등 대사질환을 치료하고 류마티스 등 자가면역질환을 치료합니다. 식품의학 교수, 임상영양 전문가, 체질 전문 한의사로 구성된 전문가들이 온전한 치료를 제공합니다. 40여 년의 연구가 집약된 객관적인 유전체 분석 알고리즘을 바탕으로 개인의 유전체 타입을 판정하고, 그에 따른 맞춤 식품·생약 처방을 전문으로 합니다.','2026-08-18'),
 ('VS2287',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2287','강남구','English, Chinese, Mongolian','유앤린성형외과는 대표원장이 직접 상담과 진료를 진행하며, 1:1 맞춤 서비스를 제공합니다. 풍부한 경험과 전문성을 갖춘 대표원장이 개별적인 요구와 필요를 철저히 분석하여, 환자에게 가장 적합한 시술과 수술만을 권유합니다. 이 같은 섬세한 접근으로 최상의 결과를 추구하며, 환자 개개인의 아름다움을 실현합니다. 또한 유앤린성형외과는 환자와의 인연을 소중히 여기며, 신뢰와 전문성을 바탕으로 특별한 변화를 만들어갑니다.','2026-08-18'),
 ('VS2286',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2286','서초구','English, Chinese, Japanese, Vietnamese, Russian, Mongolian, Arabic, Indonesian','Healing art for Beauty. 원더풀성형외과는 성형에 대한 남다른 자부심과 풍부한 임상경험에서 나오는 노하우로 고객에게 만족스러운 힐링의 순간을 만들어드립니다. 본연의 아름다움을 찾아 더 특별하게 빛날 수 있도록 원더풀성형외과는 예술가의 마음으로 최선을 다합니다. / 정밀하게 그리고 아름답게, 완벽주의 성형을 실현합니다. 원더풀성형외과는 고객 맞춤 디자인과 체계적인 시스템으로 얼굴의 변화뿐만 아니라 새로운 인생을 선물합니다.','2026-08-18'),
 ('VS2285',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2285','종로구','English, Chinese, Japanese','우주연한의원은 환자의 전체적인 건강을 고려한 통합적 접근을 지향합니다. 단순히 아픈 부분의 치료를 넘어, 환자의 이야기를 듣고 삶을 이해하며, 몸의 균형이 깨진 근본 원인을 찾아 이를 바로 잡는 데 집중합니다. 이는 환자의 영혼과 맞닿는 섬세한 손길로 이루어지며, 진정한 치유와 행복을 추구하는 것을 목표로 합니다. 우주연 한의원은 한의학의 전통적 지혜와 현대적인 치료법을 융합한 맞춤형 치료를 제공, 환자가 건강한 삶을 되찾을 수 있도록 돕습니다. 환자와의 인연을 소중히 여기며, 항상 최선을 다하는 우주연 한의원이 되겠습니다. / / 인스타그램 &gt; http://instagram.com/kdrwoojy','2026-08-18'),
 ('VS2284',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2284','도봉구','English','온아치과 강북점은 환자의 편안함과 안전함을 최우선으로 생각하는 병원입니다. 치과보철과, 구강악안면외과, 통합치의학과 등 분과별 6명의 전문 의료진이 협진을 통해 디지털 임플란트, 수면 임플란트 등을 진료합니다. 온아치과는 정직하게 진료하고 과잉 진단하지 않을 것, 항상 치아를 살리기 위해 연구할 것, 놓치는 부분이 없도록 꼼꼼하게 치료할 것, 환자가 아프지 않게 배려할 것, 소독된 기구와 장비로 청결하게 진료할 것 등 5가지 원칙을 가지고 있습니다. 환자의 편안함과 안전함을 최우선으로 생각하는 치과가 되겠습니다.','2026-08-18'),
 ('VS2283',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2283','강남구','English, Chinese, Japanese','신사역 3번 출구에 위치한 오늘성형외과 피부과는 안티에이징, 리프팅, 윤곽성형 및 윤곽 리프팅 수술을 중심으로 진료합니다. 서울대·아산병원 출신 의료진으로, / 분야별 전문 의료진들이 상담부터 수술 후 관리까지 모든 과정을 책임지는 주치의 책임 진료가 철칙입니다. 고객 만족을 최우선으로, ''건강한 아름다움''이란 모토로 / 성형외과 가져야 하는 진료철칙을 고집스럽게 지켜나가고 있습니다. 남다른 기술력과 자신감, 고객지향 철학을 바탕으로, 수술 책임 보증제를 도입해 정성을 다하고 있습니다.','2026-08-18'),
 ('VS2282',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2282','서초구','English, Japanese',NULL,'2026-08-18'),
 ('VS2281',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2281','강남구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS2279',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2279','서대문구','English, French',NULL,'2026-08-18'),
 ('VS2278',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2278','강남구','English, Chinese, Japanese, Vietnamese, Russian, Thai',NULL,'2026-08-18'),
 ('VS2277',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2277','서초구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS2276',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2276','서초구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS2275',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2275','종로구','English, Chinese, Japanese, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS2273',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2273','강남구','English, Chinese, Japanese, Vietnamese, Russian, Mongolian, Thai, Indonesian, Khmer, Malay',NULL,'2026-08-18'),
 ('VS2272',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2272','중구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS2271',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2271','서초구','English, Chinese, Japanese, Thai, Indonesian',NULL,'2026-08-18'),
 ('VS2269',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2269','강남구','English, Chinese, Japanese, Vietnamese, Russian, Mongolian, Thai, Burmese, Indonesian',NULL,'2026-08-18'),
 ('VS2268',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2268','서초구','English, Chinese, Vietnamese, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS2267',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2267','강남구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS2266',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2266','강남구','English, Chinese, Japanese, Vietnamese, Mongolian, Thai, Indonesian',NULL,'2026-08-18'),
 ('VS2265',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2265','강남구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS2264',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2264','중구','English, Chinese, Japanese, Vietnamese',NULL,'2026-08-18'),
 ('VS2262',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2262','강남구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS2238',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2238','서초구','English, Chinese, Japanese, Russian, Thai',NULL,'2026-08-18'),
 ('VS2237',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2237','서초구','English, Chinese, Japanese, Russian',NULL,'2026-08-18'),
 ('VS2236',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2236','강남구','English, Japanese',NULL,'2026-08-18'),
 ('VS2235',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2235','강남구','English',NULL,'2026-08-18'),
 ('VS2234',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2234','강남구','English, Chinese, Mongolian',NULL,'2026-08-18'),
 ('VS2233',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2233','서초구','English, Chinese, Mongolian, Thai, Indonesian',NULL,'2026-08-18'),
 ('VS2232',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2232','강남구','English, Chinese, Mongolian',NULL,'2026-08-18'),
 ('VS2231',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2231','서초구','English, Chinese, Japanese, Mongolian',NULL,'2026-08-18'),
 ('VS2230',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2230','서초구','English, Chinese, Vietnamese, Russian, Mongolian, Burmese, Indonesian, Khmer',NULL,'2026-08-18'),
 ('VS2229',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2229','강남구','English, Chinese, Japanese, Russian',NULL,'2026-08-18'),
 ('VS2228',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2228','강남구','English, German',NULL,'2026-08-18'),
 ('VS2227',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2227','영등포구','English',NULL,'2026-08-18'),
 ('VS2226',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2226','서초구','English, Chinese, Mongolian, Arabic',NULL,'2026-08-18'),
 ('VS2225',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2225','강동구','English, Chinese, Japanese, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS2224',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2224','강남구','English, Chinese, Japanese, Russian',NULL,'2026-08-18'),
 ('VS2223',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2223','은평구','English, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS2222',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2222','강남구','English, Arabic',NULL,'2026-08-18'),
 ('VS2221',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2221','영등포구','Chinese, Mongolian',NULL,'2026-08-18'),
 ('VS2111',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2111','강서구','English',NULL,'2026-08-18'),
 ('VS106',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/106','강남구','English, Japanese, Russian, Mongolian, Arabic',NULL,'2026-08-18'),
 ('VS15',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/15','서초구','English, Russian, Uzbek',NULL,'2026-08-18'),
 ('VS121',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/121','강남구','English, Russian',NULL,'2026-08-18'),
 ('VS55',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/55','송파구','English, Vietnamese, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS72',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/72','종로구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS74',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/74','강남구','English, Chinese',NULL,'2026-08-18'),
 ('VS39',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/39','강남구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS98',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/98','강남구','English, Chinese, Japanese, Russian',NULL,'2026-08-18'),
 ('VS84',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/84','영등포구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS118',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/118','노원구','English',NULL,'2026-08-18'),
 ('VS12',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/12','성동구','English, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS38',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/38','강남구','English, Russian',NULL,'2026-08-18'),
 ('VS19',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/19','용산구','English, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS40',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/40','강남구','English, Russian, Arabic',NULL,'2026-08-18'),
 ('VS24',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/24','영등포구','English, Chinese',NULL,'2026-08-18'),
 ('VS128',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/128','강남구','English, Chinese, Japanese, Vietnamese, Thai, Malay',NULL,'2026-08-18'),
 ('VS113',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/113','강남구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS9',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/9','서대문구','English, Chinese, Japanese, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS18',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/18','강서구','English, Japanese, Russian',NULL,'2026-08-18'),
 ('VS41',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/41','서초구','English, Chinese',NULL,'2026-08-18'),
 ('VS1118',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/1118','강남구','English, Chinese, Japanese, Russian, Arabic',NULL,'2026-08-18'),
 ('VS1',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/1','서초구','English, Japanese, Russian, Arabic, French',NULL,'2026-08-18'),
 ('VS11',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/11','동작구','English, Chinese, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS8',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/8','송파구','English, Chinese, Japanese, Vietnamese, Russian, Mongolian, Arabic',NULL,'2026-08-18'),
 ('VS7',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/7','종로구','English, Chinese, Russian, Mongolian, Arabic',NULL,'2026-08-18'),
 ('VS50',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/50','강남구','English, Chinese, Russian, French',NULL,'2026-08-18'),
 ('VS5',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/5','성북구','English, Russian, Mongolian, Arabic',NULL,'2026-08-18'),
 ('VS4',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/4','동대문구','English, Japanese, Russian',NULL,'2026-08-18'),
 ('VS3',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/3','광진구','English, Chinese, Russian',NULL,'2026-08-18'),
 ('VS2',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/2','강남구','English, Chinese, Japanese, Russian, Mongolian, Arabic',NULL,'2026-08-18'),
 ('VS6',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/6','강남구','English, Chinese, Vietnamese, Russian, Mongolian, Arabic',NULL,'2026-08-18'),
 ('VS25',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/25','영등포구','English, Chinese, Japanese, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS21',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/21','관악구','English, Japanese, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS20',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/20','영등포구','English, Chinese, Japanese, Mongolian',NULL,'2026-08-18'),
 ('VS17',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/17','강서구','English, Russian',NULL,'2026-08-18'),
 ('VS16',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/16','강서구','English, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS14',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/14','강동구','English, Chinese, Russian, Mongolian',NULL,'2026-08-18'),
 ('VS13',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/13','영등포구','English',NULL,'2026-08-18'),
 ('VS68',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/68','강남구','English',NULL,'2026-08-18'),
 ('VS67',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/67','종로구','English',NULL,'2026-08-18'),
 ('VS65',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/65','영등포구','English, Chinese, Japanese',NULL,'2026-08-18'),
 ('VS64',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/64','서초구','English, Chinese, Japanese, Thai, Indonesian',NULL,'2026-08-18'),
 ('VS62',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/62','강남구','English',NULL,'2026-08-18'),
 ('VS63',1,'2026-08-18','KMTPA','SEOUL','https://medical.visitseoul.net/organization/hospital/hospitalDetail/63','중구','Japanese',NULL,'2026-08-18');
